package com.hust.itss.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MajorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorAllPropertiesEquals(Major expected, Major actual) {
        assertMajorAutoGeneratedPropertiesEquals(expected, actual);
        assertMajorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorAllUpdatablePropertiesEquals(Major expected, Major actual) {
        assertMajorUpdatableFieldsEquals(expected, actual);
        assertMajorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorAutoGeneratedPropertiesEquals(Major expected, Major actual) {
        assertThat(expected)
            .as("Verify Major auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorUpdatableFieldsEquals(Major expected, Major actual) {
        assertThat(expected)
            .as("Verify Major relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMajorUpdatableRelationshipsEquals(Major expected, Major actual) {}
}
